### ISSUE TITLE
Classic Port?

### ISSUE THREAD

**Issue by wheatbread** [funkydude/MuteSoundFile#9] opened 2019-09-15 08:58 UTC
Might it be possible to make this compatible with classic?

(I tried using this version in classic, and it could not locate the sound ID 555124 (noisy mechanostrider loop found on Leatrix Tunes Classic), so I think MSF is not working in classic. :(

**Comment by no0kiee** [comment] 2019-09-15 14:35
need this addon for classic, holy spell fizzle sound make me crazy, retail version doesn't work for classic sadly

**Comment by funkydude** [comment] 2019-09-15 16:30
Duplicate of https://github.com/funkydude/MuteSoundFile/issues/8

**Closed by funkydude** 2019-09-15 16:30 UTC

**Comment by Gogo1951** [comment] 2020-01-15 17:01
You download this (https://www.curseforge.com/wow/addons/mute-wow-sounds) and drop it in your WoW Classic director under "C:\Program Files (x86)\World of Warcraft\_classic_\Sound" -- if your "Ambience" folder is at "C:\Program Files (x86)\World of Warcraft\_classic_\Sound\Ambience" then you've done it right -- and it removes all the annoying sounds like "woosh" when you mash an ability but it's not ready, or stupid hunter bird dive sounds.
